### ISSUE TITLE
An invisible links doesn't work

### ISSUE THREAD

**Issue by zloid** [mjbvz/vscode-markdown-mermaid#149]
Hi! Thanks for your work!
Please add invisible links https://mermaid-js.github.io/mermaid/#/flowchart?id=an-invisisble-link

Now this syntax does not work in the VSC:
`flowchart LR`    
    `A ~~~ B`

**Comment by rinaxsumomo** [comment]
Hi, same here. I'd like to have the invisible link as well. 
I'd appreciate your enhancement.
Thanks!

**Comment by mjbvz** [comment]
Should by fixed by 1.15.3 which picks up a new mermaid 9.2.2

**Comment by emersonmello** [comment]
Hi!

First of all, this VSCode extension is fantastic. Congratulation!

I'm using v1.17.5 (March 06, 2023). The invisible link is still not working.

Best Regards.
